app:
  tcpPort: 9000
  webSocketPort: 19000
  bossThreadSize: 1
  workThreadSize: 8
  loginModel: 3
  heartBeatTimeout: 50000 #心跳超时时间（毫秒）
  redis:
    mode: single # 单机模式：single 哨兵模式：sentinel 集群模式：cluster
    database: 3
    password:
    timeout: 3000 # 超时时间
    poolMinIdle: 8 #最小空闲数
    poolConnTimeout: 3000 # 连接超时时间(毫秒)
    poolSize: 10 # 连接池大小
    single: #redis单机配置
      address: 192.168.172.135:6379
  rabbitmq:
    host: 192.168.172.135
    port: 5672
    virtualHost: /
    userName: admin
    password: admin
  zookeeper:
    zkAddr: 192.168.172.135:2181
    zkConnectTimeOut: 20000